### Зарегистрировать игрока
POST http://127.0.0.1:8080/players
Content-Type: application/json

### Получить список игроков
GET http://127.0.0.1:8080/players
Accept: application/json

###

POST http://127.0.0.1:8080/likes/1
Accept: application/json

###

GET http://127.0.0.1:8080/likes/1
Accept: application/json

###

